<?php

use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;
use Drupal\layout_paragraphs\LayoutParagraphsSection;

/**
 * Implements hook_preprocess_hook().
 */
function mercury_editor_tabs_preprocess_me_tabs(&$vars) {
  _mercury_editor_tabs_build_layout_regions($vars);
  foreach ($vars['layout_regions'] as $region_id => $region) {
    $vars['layout_regions'][$region_id]['title_attributes']->setAttribute('data-me-accordion-tabs-draggable', $region_id);
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function mercury_editor_tabs_preprocess_me_accordion(&$vars) {
  _mercury_editor_tabs_build_layout_regions($vars);
  foreach ($vars['layout_regions'] as $region_id => $region) {
    $vars['layout_regions'][$region_id]['attributes']->setAttribute('data-me-accordion-tabs-draggable', $region_id);
  }
}

/**
 * Builds the layout region variables for tabs and accordions.
 */
function _mercury_editor_tabs_build_layout_regions(&$vars) {
  $vars['layout_regions'] = [];
  $settings = $vars['settings'];
  // Attach the builder UI if the user has access to edit the paragraph.
  if (!empty($settings['layout_paragraphs_section'])) {
    /** @var LayoutParagraphsSection */
    $layout_section = $settings['layout_paragraphs_section'];
    $paragraph = $layout_section->getEntity();
    if ($paragraph->access('update')) {
      $vars['#attached']['library'][] = 'mercury_editor_tabs/editor_ui';
    }
  }
  $vars['label_group_attributes'] = new Attribute([
    'data-me-accordion-tabs-label-group' => 'true',
  ]);
  foreach (Element::children($vars['content']) as $region_id) {
    $vars['layout_regions'][$region_id] = [
      'id' => $region_id,
      'title' => $settings['layout_regions'][$region_id]['label'],
      'title_attributes' => new Attribute([
        'data-region-label' => $region_id,
        'data-me-accordion-tabs-region-label' => $region_id,
      ]),
      'content' => $vars['content'][$region_id],
      'region' => $region_id,
      'attributes' => new Attribute([
        'data-me-region' => $region_id,
      ]),
      'content_attributes' => $vars['region_attributes'][$region_id],
    ];
  }
}
